name: RTG Take Home Assignment
on: push
runs-on: ubuntu-latest

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    name: Create infrastructure
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: |
         terraform init \
         -backend-config="bucket=${{ secrets.TFSTATE_BUCKET }}" \
         -backend-config="region=${{ secrests.TFSTATE_REGION }}" \
         -backend-config="key=${{ secrets.TFSTATE_KEY }}"
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan
      # - name: Terraform apply
      #   run: terraform apply
    
    name: Build and deploy Gatsby
    steps:
      - name: Placeholder
        run: echo "Gatsby"